services:
  sql_decomposer:
    image: omarnassif98/sql-decomposer:latest
    container_name: sql_decomposer
    ports:
      - "60001:60001"
    volumes:
      - ./config:/app/config
      - ./output:/app/output
      - ./input:/app/input
      - ./knowledge_bank:/app/knowledge_bank
      - ./logs:/app/logs
      - ./logs/injected_queries:/app/injected_queries
      - ./logs/backlink_queries:/app/backlink_queries
      - ./sandbox:/app/sandbox